[package]
name = "comfyui"
version = "0.1.0"
edition = "2024"

[dependencies]
database = { workspace = true }
err_code = { workspace = true }
inject = { workspace = true }
utils = { workspace = true }
axum_response = { workspace = true }
axum_validator = { workspace = true }

axum = { workspace = true }
axum_typed_multipart = { workspace = true }
validator = { workspace = true, features = ["derive"] }
sea-orm = { workspace = true }
nject = { workspace = true }
reqwest = { workspace = true, features = [
    "blocking",
    "json",
    "multipart",
    "cookies",
    "rustls-tls",
] }
tokio = { workspace = true, features = [] }

log = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_repr = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
tempfile = { workspace = true }


[dev-dependencies]
tokio = { workspace = true, features = [
    "macros",
    "rt-multi-thread",
    "test-util",
    "fs",
] }
anyhow = { workspace = true }
