# project: server/web 

install:
	cargo install systemfd cargo-watch

fmt:
	cargo fmt

check:
	cargo clippy

clean:
	cargo clean

run:
	cargo run

build:
	cargo build

release:
	cargo build --release

# open:
# 	open http://localhost:4000/graphql
