[package]
name = "grpc_api"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true, features = ["rt-multi-thread"] }
tower = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
tonic-health = { workspace = true }
tonic-reflection = { workspace = true }

[build-dependencies]
tonic-build = { workspace = true }
anyhow = { workspace = true }
