[package]
name = "template"
version = "0.1.0"
edition = "2024"

[dependencies]
database = { path = "../../core/database" }
code = { path = "../../core/code" }
inject = { path = "../../core/inject" }
utils = { path = "../../core/utils" }
axum_response = { path = "../../axum_response" }
axum_validator = { path = "../../axum_validator" }


axum = { workspace = true }
axum-extra = { workspace = true, features = ["cookie-private", "typed-header"] }
tonic = { workspace = true }
sea-orm = { workspace = true }
validator = { workspace = true, features = ["derive"] }
nject = { workspace = true }
chrono = { workspace = true }

log = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_repr = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }

[dev-dependencies]
orm_migration = { path = "../../core/orm_migration" }

axum-test = { workspace = true }
axum_mock = { path = "../../axum_mock" }
tokio = { workspace = true, features = [
    "macros",
    "rt-multi-thread",
    "test-util",
] }
