[package]
name = "admin"
version = "0.1.0"
edition = "2021"

[dependencies]
code = { path = "../crates/core/code" }
database = { path = "../crates/core/database" }
logger = { path = "../crates/core/logger" }
utils = { path = "../crates/core/utils" }
embed_asset = { path = "../crates/embed_asset" }
inject = { path = "../crates/core/inject" }
axum_response = { path = "../crates/axum_response" }
axum_middleware = { path = "../crates/axum_middleware" }
axum_session = { path = "../crates/axum_session" }
axum_context = { path = "../crates/axum_context" }
service_hub = { path = "../crates/service_hub" }
app_state = { path = "../crates/app_state" }

axum = { workspace = true }
axum-extra = { workspace = true, features = ["cookie-private"] }
tokio = { workspace = true, features = ["full"] }
tower = { workspace = true }
tower_governor = { workspace = true }
tower-http = { workspace = true, features = [
    "fs",
    "trace",
    "cors",
    "limit",
    "compression-gzip",
    "timeout",
    "util",
    "request-id",
] }
listenfd = { workspace = true }

tracing = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
dotenv = { workspace = true }
rust-embed = { workspace = true, features = [
    # "debug-embed",
    "include-exclude",
    "mime-guess",
] }
colored = { workspace = true }
