[package]
name = "service_hub"
version = "0.1.0"
edition = "2024"

[lib]
name = "service_hub"
path = "src/lib.rs"
crate-type = ["staticlib", "rlib"]


[dependencies]
# public = { path = "public" }
template = { path = "template" }
template_grpc = { path = "template_grpc" }
auth = { path = "auth" }
user = { path = "user" }
permission = { path = "permission" }
organization = { path = "organization" }
system = { path = "system" }
schedule = { path = "schedule" }
log = { path = "log" }
initialize = { path = "initialize" }

comfyui = { path = "comfyui" }


inject = { workspace = true }


[dev-dependencies]
tokio = { workspace = true, features = [
    "macros",
    "rt-multi-thread",
    "test-util",
] }
