syntax = "proto3";

package helloworld;

import "google/protobuf/empty.proto";
import "validate/validate.proto";

service Greeter {
  rpc SayHello(HelloRequest) returns (HelloReply) {}
  rpc SayStatus(StatusRequest) returns (google.protobuf.Empty) {}
}

message HelloRequest {
  string name = 1 [ (validate.rules).string = {min_len : 6, max_len : 10} ];
}

message HelloReply { string message = 1; }

message StatusRequest {
  // https://github.com/grpc/grpc/blob/master/doc/statuscodes.md#status-codes-and-their-use-in-grpc
  int32 code = 1;
  string message = 2;
}
