[package]
name = "public"
version = "0.1.0"
edition = "2021"

[dependencies]
axum_response = { path = "../../axum_response" }

# app_state = { path = "../../app_state" }
embed_asset = { path = "../../embed_asset" }

axum = { workspace = true }
tower-http = { workspace = true, features = ["fs"] }
tracing = { workspace = true }
