[package]
name = "axum_middleware"
version = "0.1.0"
edition = "2021"


[dependencies]
code = { path = "../core/code" }
entity = { path = "../core/entity" }
jwt = { path = "../core/jwt" }
axum_context = { path = "../axum_context" }
service_hub = { path = "../service_hub" }
axum_response = { path = "../axum_response" }

tokio = { workspace = true }
axum = { workspace = true }
axum-prometheus = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true, features = ["cors"] }
tower-sessions = { workspace = true }
http-body-util = { workspace = true }
casbin = { workspace = true }
futures = { workspace = true }
tracing = { workspace = true }
serde_json = { workspace = true }
bytes = { workspace = true }
pin-project = { workspace = true }


[dev-dependencies]
app_state = { path = "../app_state" }

tokio = { workspace = true, features = [
    "macros",
    "rt-multi-thread",
    "test-util",
] }
