[package]
name = "initialize"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
database = { path = "../../core/database" }
code = { path = "../../core/code" }
utils = { path = "../../core/utils" }
inject = { path = "../../core/inject" }
axum_response = { path = "../../axum_response" }
axum_validator = { path = "../../axum_validator" }
embed_asset = { path = "../../embed_asset" }


user = { path = "../user" }
permission = { path = "../permission" }


axum = { workspace = true }
validator = { workspace = true, features = ["derive"] }
sea-orm = { workspace = true }
nject = { workspace = true }

log = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_repr = { workspace = true }
rust-embed = { workspace = true, features = [
    # "debug-embed",
    "include-exclude",
    "mime-guess",
] }
