[package]
name = "axum_context"
version = "0.1.0"
edition = "2024"

[dependencies]
code = { path = "../core/code" }
axum_response = { path = "../axum_response" }

axum = { workspace = true }
tower = { workspace = true }
tower-sessions = { workspace = true }
tokio = { workspace = true }
bytes = { workspace = true }
tracing = { workspace = true }
serde_json = { workspace = true }
futures = { workspace = true }
