// This file is @generated by prost-build.
/// 模板 Model
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AppTemplate {}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetAppTemplatesReq {
    /// 当前分页
    #[prost(uint32, tag = "1")]
    pub page: u32,
    /// 页面大小
    #[prost(uint32, tag = "2")]
    pub page_size: u32,
    /// 开始时间
    #[prost(string, tag = "3")]
    pub start_time: ::prost::alloc::string::String,
    /// 结束时间
    #[prost(string, tag = "4")]
    pub end_time: ::prost::alloc::string::String,
    /// 排序字段
    #[prost(string, tag = "5")]
    pub order_by: ::prost::alloc::string::String,
    /// 返回有所有数据
    #[prost(bool, tag = "6")]
    pub is_all: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetAppTemplatesResp {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub msg: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub data: ::core::option::Option<get_app_templates_resp::DataList>,
}
/// Nested message and enum types in `GetAppTemplatesResp`.
pub mod get_app_templates_resp {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct DataList {
        /// 模板列表
        #[prost(message, repeated, tag = "1")]
        pub data_list: ::prost::alloc::vec::Vec<super::AppTemplate>,
        /// 总数量
        #[prost(int32, tag = "2")]
        pub total: i32,
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetAppTemplateReq {
    /// 模板ID
    #[prost(int32, tag = "1")]
    pub id: i32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetAppTemplateResp {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub msg: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub data: ::core::option::Option<AppTemplate>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateAppTemplateReq {
    /// 用户ID
    #[prost(int32, tag = "1")]
    pub user_id: i32,
    /// 描述信息
    #[prost(string, tag = "2")]
    pub desc: ::prost::alloc::string::String,
    /// 状态(false:停用,true:正常)
    #[prost(bool, tag = "3")]
    pub status: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateAppTemplateResp {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub msg: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateAppTemplateReq {
    /// 模板ID
    #[prost(int32, tag = "1")]
    pub id: i32,
    /// 用户ID
    #[prost(int32, tag = "2")]
    pub user_id: i32,
    /// 描述信息
    #[prost(string, tag = "3")]
    pub desc: ::prost::alloc::string::String,
    /// 状态(false:停用,true:正常)
    #[prost(bool, tag = "4")]
    pub status: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateAppTemplateResp {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub msg: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateAppTemplateStatusReq {
    /// 模板ID
    #[prost(int32, tag = "1")]
    pub id: i32,
    /// 状态(false:停用,true:正常)
    #[prost(bool, tag = "2")]
    pub status: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateAppTemplateStatusResp {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub msg: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteAppTemplateReq {
    /// 模板ID
    #[prost(int32, tag = "1")]
    pub id: i32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteAppTemplateResp {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub msg: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BatchDeleteAppTemplateReq {
    /// 模板ID列表
    #[prost(int32, repeated, tag = "1")]
    pub ids: ::prost::alloc::vec::Vec<i32>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BatchDeleteAppTemplateResp {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub msg: ::prost::alloc::string::String,
}
/// Generated client implementations.
pub mod app_template_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// App Template Management Service
    #[derive(Debug, Clone)]
    pub struct AppTemplateServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl AppTemplateServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> AppTemplateServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> AppTemplateServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            AppTemplateServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn get_app_templates(
            &mut self,
            request: impl tonic::IntoRequest<super::GetAppTemplatesReq>,
        ) -> std::result::Result<
            tonic::Response<super::GetAppTemplatesResp>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/template.AppTemplateService/GetAppTemplates",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("template.AppTemplateService", "GetAppTemplates"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_app_template(
            &mut self,
            request: impl tonic::IntoRequest<super::GetAppTemplateReq>,
        ) -> std::result::Result<
            tonic::Response<super::GetAppTemplateResp>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/template.AppTemplateService/GetAppTemplate",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("template.AppTemplateService", "GetAppTemplate"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn create_app_template(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateAppTemplateReq>,
        ) -> std::result::Result<
            tonic::Response<super::CreateAppTemplateResp>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/template.AppTemplateService/CreateAppTemplate",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("template.AppTemplateService", "CreateAppTemplate"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn update_app_template(
            &mut self,
            request: impl tonic::IntoRequest<super::UpdateAppTemplateReq>,
        ) -> std::result::Result<
            tonic::Response<super::UpdateAppTemplateResp>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/template.AppTemplateService/UpdateAppTemplate",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("template.AppTemplateService", "UpdateAppTemplate"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn update_app_template_status(
            &mut self,
            request: impl tonic::IntoRequest<super::UpdateAppTemplateStatusReq>,
        ) -> std::result::Result<
            tonic::Response<super::UpdateAppTemplateStatusResp>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/template.AppTemplateService/UpdateAppTemplateStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "template.AppTemplateService",
                        "UpdateAppTemplateStatus",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn delete_app_template(
            &mut self,
            request: impl tonic::IntoRequest<super::DeleteAppTemplateReq>,
        ) -> std::result::Result<
            tonic::Response<super::DeleteAppTemplateResp>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/template.AppTemplateService/DeleteAppTemplate",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("template.AppTemplateService", "DeleteAppTemplate"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn batch_delete_app_template(
            &mut self,
            request: impl tonic::IntoRequest<super::BatchDeleteAppTemplateReq>,
        ) -> std::result::Result<
            tonic::Response<super::BatchDeleteAppTemplateResp>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/template.AppTemplateService/BatchDeleteAppTemplate",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "template.AppTemplateService",
                        "BatchDeleteAppTemplate",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod app_template_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with AppTemplateServiceServer.
    #[async_trait]
    pub trait AppTemplateService: std::marker::Send + std::marker::Sync + 'static {
        async fn get_app_templates(
            &self,
            request: tonic::Request<super::GetAppTemplatesReq>,
        ) -> std::result::Result<
            tonic::Response<super::GetAppTemplatesResp>,
            tonic::Status,
        >;
        async fn get_app_template(
            &self,
            request: tonic::Request<super::GetAppTemplateReq>,
        ) -> std::result::Result<
            tonic::Response<super::GetAppTemplateResp>,
            tonic::Status,
        >;
        async fn create_app_template(
            &self,
            request: tonic::Request<super::CreateAppTemplateReq>,
        ) -> std::result::Result<
            tonic::Response<super::CreateAppTemplateResp>,
            tonic::Status,
        >;
        async fn update_app_template(
            &self,
            request: tonic::Request<super::UpdateAppTemplateReq>,
        ) -> std::result::Result<
            tonic::Response<super::UpdateAppTemplateResp>,
            tonic::Status,
        >;
        async fn update_app_template_status(
            &self,
            request: tonic::Request<super::UpdateAppTemplateStatusReq>,
        ) -> std::result::Result<
            tonic::Response<super::UpdateAppTemplateStatusResp>,
            tonic::Status,
        >;
        async fn delete_app_template(
            &self,
            request: tonic::Request<super::DeleteAppTemplateReq>,
        ) -> std::result::Result<
            tonic::Response<super::DeleteAppTemplateResp>,
            tonic::Status,
        >;
        async fn batch_delete_app_template(
            &self,
            request: tonic::Request<super::BatchDeleteAppTemplateReq>,
        ) -> std::result::Result<
            tonic::Response<super::BatchDeleteAppTemplateResp>,
            tonic::Status,
        >;
    }
    /// App Template Management Service
    #[derive(Debug)]
    pub struct AppTemplateServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> AppTemplateServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for AppTemplateServiceServer<T>
    where
        T: AppTemplateService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/template.AppTemplateService/GetAppTemplates" => {
                    #[allow(non_camel_case_types)]
                    struct GetAppTemplatesSvc<T: AppTemplateService>(pub Arc<T>);
                    impl<
                        T: AppTemplateService,
                    > tonic::server::UnaryService<super::GetAppTemplatesReq>
                    for GetAppTemplatesSvc<T> {
                        type Response = super::GetAppTemplatesResp;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetAppTemplatesReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AppTemplateService>::get_app_templates(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetAppTemplatesSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/template.AppTemplateService/GetAppTemplate" => {
                    #[allow(non_camel_case_types)]
                    struct GetAppTemplateSvc<T: AppTemplateService>(pub Arc<T>);
                    impl<
                        T: AppTemplateService,
                    > tonic::server::UnaryService<super::GetAppTemplateReq>
                    for GetAppTemplateSvc<T> {
                        type Response = super::GetAppTemplateResp;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetAppTemplateReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AppTemplateService>::get_app_template(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetAppTemplateSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/template.AppTemplateService/CreateAppTemplate" => {
                    #[allow(non_camel_case_types)]
                    struct CreateAppTemplateSvc<T: AppTemplateService>(pub Arc<T>);
                    impl<
                        T: AppTemplateService,
                    > tonic::server::UnaryService<super::CreateAppTemplateReq>
                    for CreateAppTemplateSvc<T> {
                        type Response = super::CreateAppTemplateResp;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CreateAppTemplateReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AppTemplateService>::create_app_template(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreateAppTemplateSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/template.AppTemplateService/UpdateAppTemplate" => {
                    #[allow(non_camel_case_types)]
                    struct UpdateAppTemplateSvc<T: AppTemplateService>(pub Arc<T>);
                    impl<
                        T: AppTemplateService,
                    > tonic::server::UnaryService<super::UpdateAppTemplateReq>
                    for UpdateAppTemplateSvc<T> {
                        type Response = super::UpdateAppTemplateResp;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UpdateAppTemplateReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AppTemplateService>::update_app_template(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UpdateAppTemplateSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/template.AppTemplateService/UpdateAppTemplateStatus" => {
                    #[allow(non_camel_case_types)]
                    struct UpdateAppTemplateStatusSvc<T: AppTemplateService>(pub Arc<T>);
                    impl<
                        T: AppTemplateService,
                    > tonic::server::UnaryService<super::UpdateAppTemplateStatusReq>
                    for UpdateAppTemplateStatusSvc<T> {
                        type Response = super::UpdateAppTemplateStatusResp;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UpdateAppTemplateStatusReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AppTemplateService>::update_app_template_status(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UpdateAppTemplateStatusSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/template.AppTemplateService/DeleteAppTemplate" => {
                    #[allow(non_camel_case_types)]
                    struct DeleteAppTemplateSvc<T: AppTemplateService>(pub Arc<T>);
                    impl<
                        T: AppTemplateService,
                    > tonic::server::UnaryService<super::DeleteAppTemplateReq>
                    for DeleteAppTemplateSvc<T> {
                        type Response = super::DeleteAppTemplateResp;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DeleteAppTemplateReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AppTemplateService>::delete_app_template(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DeleteAppTemplateSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/template.AppTemplateService/BatchDeleteAppTemplate" => {
                    #[allow(non_camel_case_types)]
                    struct BatchDeleteAppTemplateSvc<T: AppTemplateService>(pub Arc<T>);
                    impl<
                        T: AppTemplateService,
                    > tonic::server::UnaryService<super::BatchDeleteAppTemplateReq>
                    for BatchDeleteAppTemplateSvc<T> {
                        type Response = super::BatchDeleteAppTemplateResp;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::BatchDeleteAppTemplateReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AppTemplateService>::batch_delete_app_template(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = BatchDeleteAppTemplateSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for AppTemplateServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "template.AppTemplateService";
    impl<T> tonic::server::NamedService for AppTemplateServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
